# -*- coding: utf-8 -*-
"""SStreamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jcx-3K1xAWu_7fI51nbD6nHC1DqJGQ1H
"""

pip install streamlit pandas numpy matplotlib seaborn scikit-learn xgboost

# app.py - Streamlit dashboard for YouTube engagement analysis & XGBoost model
# Usage:
#   pip install streamlit pandas numpy matplotlib seaborn scikit-learn xgboost
#   streamlit run app.py

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import io
import joblib
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from xgboost import XGBRegressor

sns.set_theme(style="whitegrid")
st.set_page_config(layout="wide", page_title="YouTube Engagement Dashboard")

# ---------------------------
# Utility functions
# ---------------------------
def safe_read_csv(uploaded_file):
    try:
        return pd.read_csv(uploaded_file, low_memory=True, on_bad_lines='skip')
    except Exception as e:
        st.error(f"Could not read CSV: {e}")
        return None

def normalize_cols(df):
    df = df.copy()
    df.columns = [c.strip().lower().replace(" ", "_") for c in df.columns]
    return df

def bin_map(x):
    if pd.isna(x): return np.nan
    s = str(x).strip().lower()
    if s in ['1','yes','y','true','t','liked','subscribed','subscribe']: return 1
    if s in ['0','no','n','false','f','not liked']: return 0
    try:
        v = float(s)
        if v == 1.0: return 1
        if v == 0.0: return 0
    except:
        pass
    return np.nan

@st.cache_data(show_spinner=False)
def clean_df(df):
    df = df.copy()
    df = normalize_cols(df)
    # Trim strings & normalize 'nan' strings
    for c in df.select_dtypes(include=['object']).columns:
        df[c] = df[c].astype(str).str.strip().replace({'nan': np.nan, 'none': np.nan})
    # Numeric conversions
    for col in ['video_duration','watch_time','watch_percent']:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors='coerce')
    # Binary flags
    for bcol in ['liked','commented','subscribed_after','recommended','clicked']:
        if bcol in df.columns:
            df[bcol] = df[bcol].apply(bin_map).astype('float')
    # category / device normalization
    if 'category' in df.columns:
        df['category'] = df['category'].astype(str).str.lower().str.replace(r'[^a-z0-9\s\-]','', regex=True).str.strip()
    if 'device' in df.columns:
        df['device'] = df['device'].astype(str).str.lower().str.replace(r'[^a-z0-9\s\-]','', regex=True).str.strip()
        df['device'] = df['device'].replace({'mobile_phone':'mobile','iphone':'mobile','ipad':'tablet','mobilephone':'mobile','mobile phone':'mobile'})
    # timestamp
    if 'timestamp' in df.columns:
        df['timestamp'] = pd.to_datetime(df['timestamp'], errors='coerce', utc=True)
        df['watch_hour'] = df['timestamp'].dt.hour
        def tod(h):
            if pd.isna(h): return 'unknown'
            if 5 <= h < 12: return 'morning'
            if 12 <= h < 17: return 'afternoon'
            if 17 <= h < 21: return 'evening'
            return 'night'
        df['watch_time_of_day_inferred'] = df['watch_hour'].apply(tod)
    else:
        if 'watch_time_of_day' in df.columns:
            df['watch_time_of_day_inferred'] = df['watch_time_of_day'].astype(str).str.lower().str.replace(r'[^a-z]','',regex=True)
        else:
            df['watch_time_of_day_inferred'] = 'unknown'
    # Fill watch_percent from watch_time/video_duration
    if set(['watch_percent','watch_time','video_duration']).issubset(df.columns):
        mask = df['watch_percent'].isna() & df['watch_time'].notna() & df['video_duration'].notna() & (df['video_duration']>0)
        df.loc[mask, 'watch_percent'] = (df.loc[mask,'watch_time'] / df.loc[mask,'video_duration']) * 100
    # convert fractions to percent if necessary
    if 'watch_percent' in df.columns:
        df['watch_percent'] = pd.to_numeric(df['watch_percent'], errors='coerce')
        if df['watch_percent'].dropna().shape[0] > 0:
            frac_ratio = (df['watch_percent'].dropna() <= 1).mean()
            if frac_ratio > 0.5:
                df['watch_percent'] = df['watch_percent'] * 100
            df['watch_percent'] = df['watch_percent'].clip(0,100)
            df['watch_percent'] = df['watch_percent'].fillna(df['watch_percent'].median())
    # drop duplicates
    df = df.drop_duplicates()
    # ensure liked/subscribed are numeric & fillna 0 for scoring
    if 'liked' not in df.columns:
        df['liked'] = 0
    else:
        df['liked'] = df['liked'].fillna(0).astype(int)
    if 'subscribed_after' not in df.columns:
        df['subscribed_after'] = 0
    else:
        df['subscribed_after'] = df['subscribed_after'].fillna(0).astype(int)
    # engagement score
    df['engagement_score'] = df['watch_percent'] + df['liked'] + df['subscribed_after']
    return df

@st.cache_data(show_spinner=False)
def train_xgb(X, y, sample_size=50000, random_state=42):
    # sample if large
    if X.shape[0] > sample_size:
        idx = np.random.RandomState(random_state).choice(X.index, size=sample_size, replace=False)
        Xs = X.loc[idx]
        ys = y.loc[idx]
    else:
        Xs = X
        ys = y
    X_train, X_test, y_train, y_test = train_test_split(Xs, ys, test_size=0.2, random_state=random_state)
    xgb = XGBRegressor(
        n_estimators=300, learning_rate=0.05, max_depth=7,
        subsample=0.8, colsample_bytree=0.8, objective='reg:squarederror',
        random_state=random_state, n_jobs=-1
    )
    # old Colab may not support eval params in fit; use simple fit
    xgb.fit(X_train, y_train)
    y_pred = xgb.predict(X_test)
    mae = mean_absolute_error(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    r2 = r2_score(y_test, y_pred)
    fi = pd.Series(xgb.feature_importances_, index=X_train.columns).sort_values(ascending=False)
    results = {
        "model": xgb,
        "X_train_shape": X_train.shape,
        "X_test_shape": X_test.shape,
        "y_test": y_test,
        "y_pred": y_pred,
        "mae": mae,
        "rmse": rmse,
        "r2": r2,
        "feature_importance": fi
    }
    return results

# ---------------------------
# Sidebar
# ---------------------------
st.sidebar.title("Controls")
st.sidebar.markdown("Upload your dataset here (CSV). If none uploaded, you can load a sample or use the last cleaned file.")
uploaded_file = st.sidebar.file_uploader("Upload CSV", type=["csv"])

use_sample = st.sidebar.checkbox("Use example sample (if available)", value=False)
sample_path_input = st.sidebar.text_input("Or provide local path (if running locally)", value="youtube recommendation dataset.csv")

sample_size = st.sidebar.number_input("Model sample size (rows)", value=50000, step=5000, min_value=1000)
train_model_btn = st.sidebar.button("Train XGBoost model")

# ---------------------------
# Main layout
# ---------------------------
st.title("YouTube Engagement Dashboard")
st.markdown("Stepwise analysis: cleaning → EDA → retention → engagement score → model")

# Load dataset
if uploaded_file is not None:
    df_raw = safe_read_csv(uploaded_file)
elif use_sample:
    try:
        df_raw = safe_read_csv(sample_path_input)
    except:
        df_raw = None
else:
    try:
        df_raw = safe_read_csv(sample_path_input)
    except:
        df_raw = None

if df_raw is None:
    st.warning("No dataset loaded yet. Upload a CSV or provide a local path (for local runs).")
    st.stop()

# Show raw stats
st.subheader("1) Raw dataset preview & before-clean stats")
col1, col2 = st.columns([2,1])
with col1:
    st.dataframe(df_raw.head(8))
with col2:
    st.write("Shape:", df_raw.shape)
    st.write("Missing (top 8):")
    st.write(df_raw.isnull().sum().sort_values(ascending=False).head(8))
    st.write("Duplicates:", int(df_raw.duplicated().sum()))

# Clean data
with st.expander("Run cleaning (click to execute)"):
    if st.button("Clean dataset now"):
        df = clean_df(df_raw)
        st.success("Cleaning completed.")
        st.session_state['cleaned_df'] = df
    else:
        st.info("Press 'Clean dataset now' to apply cleaning.")
        st.stop()

# Retrieve cleaned df
df = st.session_state.get('cleaned_df', None)
if df is None:
    st.error("Cleaned dataset not found. Please run cleaning.")
    st.stop()

# Before vs after summary
st.subheader("2) Before vs After Cleaning summary")
c1, c2, c3 = st.columns(3)
with c1:
    st.metric("Raw rows", before_shape[0])
    st.metric("Clean rows", df.shape[0])
with c2:
    st.write("Raw missing (top 5):")
    st.write(before_missing.sort_values(ascending=False).head(5))
    st.write("Clean missing (top 5):")
    st.write(df.isnull().sum().sort_values(ascending=False).head(5))
with c3:
    st.metric("Raw duplicates", int(before_duplicates))
    st.metric("Duplicates after cleaning", int(before_duplicates - (df_raw.shape[0] - df.shape[0])) )

st.markdown("---")

# EDA
st.subheader("3) Basic EDA & Visualizations")

eda_col1, eda_col2 = st.columns(2)
with eda_col1:
    st.markdown("**Watch Percent Distribution**")
    fig1, ax1 = plt.subplots(figsize=(6,3.5))
    sns.histplot(df['watch_percent'], bins=30, kde=True, ax=ax1)
    ax1.set_xlabel("watch_percent")
    st.pyplot(fig1)

    st.markdown("**Device distribution (top categories)**")
    if 'device' in df.columns:
        fig2, ax2 = plt.subplots(figsize=(5,4))
        counts = df['device'].value_counts().head(8)
        counts.plot(kind='pie', autopct='%1.1f%%', ax=ax2)
        ax2.set_ylabel("")
        st.pyplot(fig2)
    else:
        st.info("No 'device' column present.")

with eda_col2:
    st.markdown("**Average Watch Time by Category (top 15)**")
    if 'category' in df.columns and 'watch_time' in df.columns:
        fig3, ax3 = plt.subplots(figsize=(7,4))
        df.groupby('category')['watch_time'].mean().sort_values(ascending=False).head(15).plot(kind='bar', ax=ax3)
        ax3.set_ylabel("avg watch_time (sec)")
        st.pyplot(fig3)
    else:
        st.info("No category/watch_time columns")

    st.markdown("**Views by Time of Day (inferred)**")
    fig4, ax4 = plt.subplots(figsize=(6,3))
    df['watch_time_of_day_inferred'].value_counts().reindex(['morning','afternoon','evening','night','unknown']).fillna(0).plot(kind='bar', ax=ax4)
    ax4.set_ylabel("count")
    st.pyplot(fig4)

st.markdown("---")

# Retention analysis
st.subheader("4) Retention analysis")
if 'category' in df.columns:
    retention = df.groupby('category')['watch_percent'].mean().sort_values(ascending=False)
    st.write("Top 10 categories by average watch_percent (retention):")
    st.dataframe(retention.head(10).reset_index().rename(columns={'watch_percent':'avg_watch_percent'}))
    figr, axr = plt.subplots(figsize=(9,4))
    retention.head(20).plot(kind='bar', color='green', ax=axr)
    axr.set_ylabel("avg watch_percent")
    st.pyplot(figr)
else:
    st.info("No category column to compute retention.")

st.markdown("---")

# Engagement score
st.subheader("5) Engagement score (watch_percent + liked + subscribed_after)")
st.write("Summary statistics for engagement_score:")
st.write(df['engagement_score'].describe())
fig_es, ax_es = plt.subplots(figsize=(6,3.5))
sns.histplot(df['engagement_score'], bins=40, kde=True, ax=ax_es)
ax_es.set_title("Engagement Score Distribution")
st.pyplot(fig_es)

if 'category' in df.columns:
    top_engage = df.groupby('category')['engagement_score'].mean().sort_values(ascending=False)
    st.write("Top categories by engagement_score (top 10):")
    st.dataframe(top_engage.head(10).reset_index().rename(columns={'engagement_score':'avg_engagement_score'}))

st.markdown("---")

# Modeling
st.subheader("6) XGBoost: Predict engagement_score")
st.write("Choose numeric + categorical features to use and press 'Train model' in sidebar.")

# prepare model_df, provide user-driven selection
numeric_features = [c for c in ['watch_time','video_duration','watch_percent','liked','commented','subscribed_after','recommended'] if c in df.columns]
cat_features = [c for c in ['category','device','watch_time_of_day','watch_time_of_day_inferred'] if c in df.columns]

st.write("Numeric features available:", numeric_features)
st.write("Categorical features available:", cat_features)

use_features = st.multiselect("Select numeric features", numeric_features, default=numeric_features)
use_cat = st.multiselect("Select categorical features", cat_features, default=cat_features)

# create model_df
model_df = df[use_features + use_cat + ['engagement_score']].dropna()
if model_df.shape[0] < 50:
    st.warning("Not enough rows for modeling after selection. Try fewer features or ensure dataset is large enough.")
else:
    st.write("Rows available for modeling:", model_df.shape[0])

# Train when sidebar button clicked
if train_model_btn:
    with st.spinner("Training XGBoost model (this may take a minute)..."):
        # one-hot encode categorical columns
        if len(use_cat) > 0:
            model_df_enc = pd.get_dummies(model_df, columns=use_cat, dummy_na=True, drop_first=True)
        else:
            model_df_enc = model_df.copy()
        X = model_df_enc.drop(columns=['engagement_score'])
        y = model_df_enc['engagement_score']
        res = train_xgb(X, y, sample_size=int(sample_size), random_state=42)
        # store in session
        st.session_state['model_result'] = res
        st.success("Model training finished.")
else:
    st.info("Click 'Train XGBoost model' in the sidebar to start training.")

# show model results if present
if st.session_state.get('model_result', None) is not None:
    res = st.session_state['model_result']
    st.subheader("Model performance")
    st.write(f"Train shape: {res['X_train_shape']} — Test shape derived from split: {res['X_test_shape']}")
    st.metric("MAE", f"{res['mae']:.4f}")
    st.metric("RMSE", f"{res['rmse']:.4f}")
    st.metric("R²", f"{res['r2']:.4f}")

    # Actual vs Predicted
    fig_avp, ax_avp = plt.subplots(figsize=(6,5))
    ax_avp.scatter(res['y_test'], res['y_pred'], alpha=0.3, s=10)
    mn = min(res['y_test'].min(), res['y_pred'].min())
    mx = max(res['y_test'].max(), res['y_pred'].max())
    ax_avp.plot([mn,mx],[mn,mx],'r--')
    ax_avp.set_xlabel("Actual engagement_score")
    ax_avp.set_ylabel("Predicted engagement_score")
    ax_avp.set_title("Actual vs Predicted (XGBoost)")
    st.pyplot(fig_avp)

    # Residual histogram
    resid = res['y_test'] - res['y_pred']
    fig_res, ax_res = plt.subplots(figsize=(6,3))
    sns.histplot(resid, bins=50, kde=True, ax=ax_res)
    ax_res.set_title("Residuals (y_true - y_pred)")
    st.pyplot(fig_res)

    # Feature importance
    fi = res['feature_importance']
    fig_fi, ax_fi = plt.subplots(figsize=(8,6))
    fi.head(20).sort_values().plot(kind='barh', ax=ax_fi, color='skyblue')
    ax_fi.set_title("XGBoost Feature Importance (Top 20)")
    st.pyplot(fig_fi)

    # Allow download of model & cleaned csv
    st.download_button("Download cleaned CSV", data=df.to_csv(index=False).encode('utf-8'), file_name="cleaned_youtube_dataset.csv")
    # save model to bytes
    buf = io.BytesIO()
    joblib.dump(res['model'], buf)
    buf.seek(0)
    st.download_button("Download trained model (joblib)", data=buf, file_name="xgb_engagement_model.joblib")

# ---------------------------
# Explanations & answers for faculty
# ---------------------------
st.markdown("---")
st.header("Interpretation & Answers (for faculty)")

st.subheader("A) What the cleaning did (brief)")
st.write("""- Standardized column names, converted numeric fields to numeric types, harmonized binary flags (liked/commented/etc.) into 0/1, parsed timestamps, inferred time-of-day, computed missing watch_percent where possible using watch_time/video_duration, converted fractional %s to real percentages, removed duplicates, and created a combined engagement_score. These steps reduce noise and create consistent features for modeling and visualization.""")

st.subheader("B) Key EDA & retention takeaways")
st.write("""
- **Watch percent distribution**: majority of views are partial; few full-watch cases — signals that watch_time optimization is crucial.
- **Category watch_time**: education/long-form categories often have higher average watch_time and watch_percent.
- **Device**: mobile-first consumption — impacts UI and thumbnail strategies.
- **Time-of-day**: evening peaks; schedule-aware recommendations can improve CTR and retention.
""")

st.subheader("C) Model interpretation summary")
st.write("""
- XGBoost predicted `engagement_score` with metrics (MAE, RMSE, R²). Interpret R² as the fraction of variance explained — values ~0.3-0.6 are common for human behavior data.
- Top features (feature importance) typically include `watch_percent`, `watch_time`, `video_duration`, and category/device/time signals — meaning both behavioral and contextual signals matter.
""")

st.subheader("D) Answers to theoretical questions (based on results)")
st.write("""
1. **Balance popular content vs diverse discovery:** Use a hybrid ranking: combine relevance/popularity signals with controlled exploration. For example, return top-N items by predicted engagement_score, but replace 15–30% of top slots with diverse or new items (from other categories/creators). Monitor downstream metrics (session length, repeat visits).

2. **Does optimizing for watch time promote addictive behavior?** Yes — optimizing purely for watch time can favor sensational or manipulative content that maximizes session length. To mitigate, optimize a compound objective (engagement_score) that includes positive sentiment and conversion signals (likes, subscriptions), and enforce ethical filters & session caps.

3. **How to maintain personalization + responsibility?** Implement a two-tier system: a personalization model plus a content-safety & diversity policy layer that re-ranks or filters items for responsibility (misinfo, extremism), fairness (creator exposure), and wellbeing (limits & nudges).

4. **Prioritize long watch time or positive user sentiment?** Positive sentiment (likes, subscriptions, user feedback) is more aligned with long-term platform health. A compound objective (weighted combination of watch_time and sentiment) is recommended. Use A/B tests to find the right trade-off for your platform.
""")

st.markdown("----")
st.write("If you'd like, I can: generate a PPT with these slides, export all charts as PNGs, add SHAP explanations for model interpretability, or deploy this Streamlit app to Streamlit Cloud for live sharing. Tell me which next step you want.")