# -*- coding: utf-8 -*-
"""SStreamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jcx-3K1xAWu_7fI51nbD6nHC1DqJGQ1H
"""

# ===================== ZIP + CSV LOADER ======================
import zipfile
import io

def load_file(uploaded_file):
    """Load CSV directly or extract CSV from ZIP."""
    if uploaded_file is None:
        return None

    filename = uploaded_file.name.lower()

    # --- CASE 1: CSV directly uploaded ---
    if filename.endswith(".csv"):
        try:
            return pd.read_csv(uploaded_file, low_memory=True, on_bad_lines="skip")
        except Exception as e:
            st.error(f"❌ Error reading CSV: {e}")
            return None

    # --- CASE 2: ZIP uploaded ---
    if filename.endswith(".zip"):
        try:
            z = zipfile.ZipFile(uploaded_file)
            files_inside = z.namelist()

            # Find first CSV inside ZIP
            csv_files = [f for f in files_inside if f.lower().endswith(".csv")]

            if len(csv_files) == 0:
                st.error("❌ ZIP file contains no CSV.")
                return None

            csv_to_read = csv_files[0]
            st.success(f"📄 Found CSV inside ZIP: {csv_to_read}")

            with z.open(csv_to_read) as f:
                return pd.read_csv(f, low_memory=True, on_bad_lines="skip")

        except Exception as e:
            st.error(f"❌ Error reading ZIP: {e}")
            return None

    st.error("❌ Unsupported file type. Upload CSV or ZIP.")
    return None

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import io
import joblib
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from xgboost import XGBRegressor

sns.set_theme(style="whitegrid")
st.set_page_config(layout="wide", page_title="YouTube Engagement Dashboard")

# ---------------------------
# Utility functions
# ---------------------------
def safe_read_csv(uploaded_file):
    try:
        return pd.read_csv(uploaded_file, low_memory=True, on_bad_lines='skip')
    except Exception as e:
        st.error(f"Could not read CSV: {e}")
        return None

def normalize_cols(df):
    df = df.copy()
    df.columns = [c.strip().lower().replace(" ", "_") for c in df.columns]
    return df

def bin_map(x):
    if pd.isna(x): return np.nan
    s = str(x).strip().lower()
    if s in ['1','yes','y','true','t','liked','subscribed','subscribe']: return 1
    if s in ['0','no','n','false','f','not liked']: return 0
    try:
        v = float(s)
        if v == 1.0: return 1
        if v == 0.0: return 0
    except:
        pass
    return np.nan

@st.cache_data(show_spinner=False)
def clean_df(df):
    df = df.copy()
    df = normalize_cols(df)
    # Trim strings & normalize
    for c in df.select_dtypes(include=['object']).columns:
        df[c] = df[c].astype(str).str.strip().replace({'nan': np.nan, 'none': np.nan})
    # Numeric conversions
    for col in ['video_duration','watch_time','watch_percent']:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors='coerce')
    # Binary flags
    for bcol in ['liked','commented','subscribed_after','recommended','clicked']:
        if bcol in df.columns:
            df[bcol] = df[bcol].apply(bin_map).astype('float')
    # category / device cleaning
    if 'category' in df.columns:
        df['category'] = df['category'].astype(str).str.lower().str.replace(r'[^a-z0-9\s\-]','', regex=True).str.strip()
    if 'device' in df.columns:
        df['device'] = df['device'].astype(str).str.lower().str.replace(r'[^a-z0-9\s\-]','', regex=True).str.strip()
        df['device'] = df['device'].replace({'mobile_phone':'mobile','iphone':'mobile','ipad':'tablet','mobilephone':'mobile','mobile phone':'mobile'})
    # timestamp cleaning
    if 'timestamp' in df.columns:
        df['timestamp'] = pd.to_datetime(df['timestamp'], errors='coerce', utc=True)
        df['watch_hour'] = df['timestamp'].dt.hour
        def tod(h):
            if pd.isna(h): return 'unknown'
            if 5 <= h < 12: return 'morning'
            if 12 <= h < 17: return 'afternoon'
            if 17 <= h < 21: return 'evening'
            return 'night'
        df['watch_time_of_day_inferred'] = df['watch_hour'].apply(tod)
    else:
        df['watch_time_of_day_inferred'] = 'unknown'

    # Fill watch_percent
    if set(['watch_percent','watch_time','video_duration']).issubset(df.columns):
        mask = df['watch_percent'].isna() & df['video_duration'].gt(0)
        df.loc[mask, 'watch_percent'] = (df.loc[mask,'watch_time'] / df.loc[mask,'video_duration']) * 100

    # convert fractions to percent
    if 'watch_percent' in df.columns:
        df['watch_percent'] = pd.to_numeric(df['watch_percent'], errors='coerce')
        if df['watch_percent'].dropna().shape[0] > 0:
            frac_ratio = (df['watch_percent'].dropna() <= 1).mean()
            if frac_ratio > 0.5:
                df['watch_percent'] *= 100
        df['watch_percent'] = df['watch_percent'].clip(0,100)
        df['watch_percent'] = df['watch_percent'].fillna(df['watch_percent'].median())

    df = df.drop_duplicates()

    df['liked'] = df['liked'].fillna(0).astype(int)
    df['subscribed_after'] = df['subscribed_after'].fillna(0).astype(int)

    df['engagement_score'] = df['watch_percent'] + df['liked'] + df['subscribed_after']
    return df


@st.cache_data(show_spinner=False)
def train_xgb(X, y, sample_size=50000, random_state=42):
    if X.shape[0] > sample_size:
        idx = np.random.RandomState(random_state).choice(X.index, size=sample_size, replace=False)
        Xs = X.loc[idx]
        ys = y.loc[idx]
    else:
        Xs = X
        ys = y

    X_train, X_test, y_train, y_test = train_test_split(Xs, ys, test_size=0.2, random_state=random_state)

    xgb = XGBRegressor(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=7,
        subsample=0.8,
        colsample_bytree=0.8,
        objective='reg:squarederror',
        random_state=random_state,
        n_jobs=-1
    )

    # Older XGBoost version → simple fit
    xgb.fit(X_train, y_train)

    y_pred = xgb.predict(X_test)

    mae = mean_absolute_error(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    r2 = r2_score(y_test, y_pred)

    fi = pd.Series(xgb.feature_importances_, index=X_train.columns).sort_values(ascending=False)

    return {
        "model": xgb,
        "X_train_shape": X_train.shape,
        "X_test_shape": X_test.shape,
        "y_test": y_test,
        "y_pred": y_pred,
        "mae": mae,
        "rmse": rmse,
        "r2": r2,
        "feature_importance": fi
    }